# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_user',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('LoginName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('PetName', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
    ]
